name: felisitas_project_uas
description: Aplikasi Sistem Informasi Akademik - UAS
publish_to: "none"
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  intl: ^0.18.1
  pdf: ^3.11.0
  printing: ^5.10.0
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
