name: felisitas_project_uas
description: Aplikasi Sistem Informasi Akademik - UAS
publish_to: "none"
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0          # State Management
  sqflite: ^2.2.0           # Local Storage
  path: ^1.8.0              # Helper path database
  shared_preferences: ^2.2.0 # Simpan sesi login sederhana
  pdf: ^3.10.0              # Ekspor PDF
  printing: ^5.11.0         # Print/Share PDF
  fl_chart: ^0.63.0         # Ekstra Poin: Grafik
  google_fonts: ^5.0.0      # UI/UX
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
